services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: pawmatch
      POSTGRES_USER: pawuser
      POSTGRES_PASSWORD: pawpass
    ports:
      - "5432:5432"
