# Generated by Django 6.0.3 on 2026-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("size", models.IntegerField()),
                ("energy", models.IntegerField()),
                ("grooming", models.IntegerField()),
                ("kids_friendly", models.IntegerField()),
                ("housing", models.CharField(max_length=50)),
            ],
        ),
    ]
