# Generated by Django 6.0.3 on 2026-03-09 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="energy",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="grooming",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="housing",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="breed",
            name="kids_friendly",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="size",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ]
            ),
        ),
    ]
