# Generated by Django 6.0.3 on 2026-03-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0002_alter_breed_energy_alter_breed_grooming_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="housing",
            field=models.CharField(
                choices=[
                    ("Apartment", "apartment"),
                    ("House", "house"),
                    ("both", "Apartment or House"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
