# Generated by Django 6.0.3 on 2026-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0003_alter_breed_housing_alter_breed_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="housing",
            field=models.CharField(
                choices=[
                    ("Apartment", "apartment"),
                    ("House", "house"),
                    ("both", "apartment or house"),
                ],
                max_length=20,
            ),
        ),
    ]
