# Generated by Django 6.0.3 on 2026-03-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0004_alter_breed_housing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="energy",
            field=models.IntegerField(
                choices=[
                    (1, "1 - very low"),
                    (2, "2 - low"),
                    (3, "3 - medium"),
                    (4, "4 - high"),
                    (5, "5 - very high"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="grooming",
            field=models.IntegerField(
                choices=[
                    (1, "1 - very low"),
                    (2, "2 - low"),
                    (3, "3 - medium"),
                    (4, "4 - high"),
                    (5, "5 - very high"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="housing",
            field=models.CharField(
                choices=[
                    ("Apartment", "apartment"),
                    ("House", "house"),
                    ("both", "apartment or house"),
                ],
                default="both",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="kids_friendly",
            field=models.IntegerField(
                choices=[
                    (1, "1 - very low"),
                    (2, "2 - low"),
                    (3, "3 - medium"),
                    (4, "4 - high"),
                    (5, "5 - very high"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="size",
            field=models.IntegerField(
                choices=[(1, "small"), (2, "medium"), (3, "large")]
            ),
        ),
    ]
