# Generated by Django 6.0.3 on 2026-03-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0005_alter_breed_energy_alter_breed_grooming_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="breed",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
