# Generated by Django 6.0.3 on 2026-03-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0006_breed_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="breed",
            old_name="housing",
            new_name="housing_type",
        ),
        migrations.AddField(
            model_name="breed",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="breed",
            name="energy",
            field=models.IntegerField(
                choices=[
                    (1, "very low"),
                    (2, "low"),
                    (3, "medium"),
                    (4, "high"),
                    (5, "very high"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="grooming",
            field=models.IntegerField(
                choices=[
                    (1, "very low"),
                    (2, "low"),
                    (3, "medium"),
                    (4, "high"),
                    (5, "very high"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="kids_friendly",
            field=models.IntegerField(
                choices=[
                    (1, "very low"),
                    (2, "low"),
                    (3, "medium"),
                    (4, "high"),
                    (5, "very high"),
                ]
            ),
        ),
    ]
