# Generated by Django 6.0.3 on 2026-03-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0009_quizresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="housing_type",
            field=models.CharField(
                choices=[
                    ("Apartment", "apartment"),
                    ("House", "house"),
                    ("Apartment/House", "apartment/house"),
                ],
                default="Apartment/House",
            ),
        ),
    ]
