# Generated by Django 6.0.3 on 2026-04-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0010_alter_breed_housing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="breed",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="breeds/"),
        ),
    ]
