# Generated by Django 6.0.3 on 2026-04-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0011_breed_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="breed",
            name="comparison_description",
            field=models.CharField(
                blank=True,
                help_text="Short Comparison description for the breed",
                max_length=435,
                null=True,
            ),
        ),
    ]
