# Generated by Django 6.0.3 on 2026-04-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0012_breed_comparison_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="comparison_description",
            field=models.TextField(
                blank=True,
                help_text="Short Comparison description for the breed",
                max_length=435,
                null=True,
            ),
        ),
    ]
