# Generated by Django 6.0.3 on 2026-04-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0013_alter_breed_comparison_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.CharField(max_length=435)),
                ('first_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_first', to='breeds.breed')),
                ('second_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_second', to='breeds.breed')),
            ],
            options={
                'unique_together': {('first_breed', 'second_breed')},
            },
        ),
    ]
