# Generated by Django 6.0.3 on 2026-04-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0014_breedcomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedcomparison',
            name='conclusion',
            field=models.TextField(max_length=435),
        ),
    ]
